-- CreateTable
CREATE TABLE `allProject` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `img` VARCHAR(400) NULL,
    `proj_title` VARCHAR(100) NOT NULL,
    `proj_des` VARCHAR(300) NOT NULL,
    `live_link` VARCHAR(300) NOT NULL,
    `createdAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updatedAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
